services:
  - type: web
    name: asa-laravel
    runtime: php
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install --no-dev --optimize-autoloader
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql313.byethost7.com
      - key: DB_DATABASE
        value: b7_38382197_asa
      - key: DB_USERNAME
        value: b7_38382197
      - key: DB_PASSWORD
        value: Jeanbac2017!
